# Generated by Django 5.0.4 on 2024-08-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_genre_news_url_news_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='news',
            name='url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='year',
        ),
    ]
